### ISSUE TITLE
Orderbook with additionals colums like bitcoin accumulated amount

### ISSUE THREAD

**Issue by chebetos** [blinktrade/bitex#16]
Me gustaría que se mostrase el acumulado de bitcoins ofertados / demandados, como en la imagen que adjunto.

![ordenes](https://cloud.githubusercontent.com/assets/1843260/4732468/4cac75e0-59bc-11e4-9013-9044a60d0521.png)

Y si no puede ser en la página principal, tal vez en una página secundaria, un libro de ordenes ampliado, que además del acumulado de bitcoins ofertados, muestre cuanto es la cantidad de BsF requerida para esa oferta y/o para esa oferta y las superiores, y además la tasa promedio de adquisición, adjunto ejemplo.

De esta imagen puedo concluir que un poco menos de 118.000 BsF puedo comprar los 2,19 BTC ofertados a una tasa promedio de 53820,32

O si quiero mantenerme en una tasa razonable, adquirir hasta la oferta de 0,1 BTC de Yosemir (cuarta de abajo hacia arriba); donde con 66334,48 BsF puedo adquirir 1,63163 BTC a una tasa promedio de 40655 BsF/BTC.

![ordenes2](https://cloud.githubusercontent.com/assets/1843260/4732479/6e0b380c-59bc-11e4-87e6-96f177f0e7b2.png)

**Comment by pinhopro** [comment]
Implemented since January.  Marking this as closed.
