### ISSUE TITLE
Update example config (`config/bitex.ini.example`)

### ISSUE THREAD

**Issue by pjz** [blinktrade/bitex#20]
Hi, when I did
```
$ ./apps/ws_gateway/main.py -i ws_gateway -c config/myconfig.ini
```
I got
`AttributeError: 'ProjectOptions' object has no attribute 'url_payment_processor'`

even though the included `config/bitex.ini.example` doesn't have that key in the `[ws_gateway_xxx]` section.  Is there an updated example config someone could add?  I can add this one key, but it's unclear to me if all the sections are still valid, much less individual keys.  Thanks!

**Comment by pinhopro** [comment]
You have to install pyblinktrade ( https://github.com/blinktrade/pyblinktrade )

**Comment by pjz** [comment]
It's installed. Moving the `url_payment_processor` line up to the default section fixed it.

**Comment by pjz** [comment]
Okay, so now I'm having issues because there's no bootstrap data in the database. I've tried adding some, but the relationship between brokers and users is unclear, as is whether that's the same broker_id needed in `frontend/_config.yml`.  Any chance you guys could post a set of demo data, or perhaps put something useful in `trade/models.py:db_bootstrap` ?

**Comment by pinhopro** [comment]
https://github.com/blinktrade/bitex/tree/master/config/bootstrap

**Comment by pinhopro** [comment]
just run  
$ bootstap.py demo.ini 

It should work

**Comment by pjz** [comment]
Wow, I was too busy reading `apps/trade/models.py` to notice! Will do, thanks!

**Comment by pinhopro** [comment]
Not so sure if the demo.ini is up to date, but you should be able to work with it. 

let me know if it works or not :)

**Comment by pjz** [comment]
Seems to work okay, except that I can only log in as the demo `user` user not as the `exchange` user. Any hints?

**Comment by pinhopro** [comment]
the generated password for the exchange user is a random password.

just make sure you include "password" key in the config file

**Comment by pjz** [comment]
I used the `demo.ini`, and it implies that the `exchange` user password is `abc12345`... is that the config file you were referring to?

**Comment by pjz** [comment]
Okay, the password issue I was me not noticing that you had to go tot he #admin URL to log in as admin.
