### ISSUE TITLE
Need API documentation

### ISSUE THREAD

**Issue by amingilani** [blinktrade/bitex#7]
Need an API for automated exchange bots. This increases trading and helps make the market more efficient.

**Comment by amingilani** [comment]
@pinhopro it's been near a year that you said you'd be working on your documentation "very soon". I've emailed, lobbied, and asked multiple times.

I've read the obscure Gist detailing the Restful API, i even know know where the typos are. No, i don't want to read your client and try to understand how the websockets function, I need documentation.

Are you going to publish the documentation anytime soon, or will this issue be ignored for another year or two?

**Comment by pinhopro** [comment]
@amingilani Our resources are very limited to put focus on writing documentation to developers that don't want to read our client implementation.

If you are interested in contributing with the project, please add me on skype, so I can give you a overview.  

Thanks,
Rodrigo

**Comment by amingilani** [comment]
@pinhopro, oh i've read the code implementation, multiple times. I've had other devs take a look too, but my forte is documented code.

**I've emailed you**, already messaged you **on Skype**, and even **had bitex-powered exchange try to reach you.** It's beyond me how you still don't remember me reaching out through all these channels and would like me to repeat my actions.

I've managed projects myself. Priority issues open for a year are **not** because you're unable, but because you're **incompetent**. Please, either write a documentation and publish it on the website **(not a far away obscure Gist that details half the api, and is full of typos and errors in the sample implementation)**

**or man up and tell your community that you don't care about them**

**Comment by amingilani** [comment]
If you choose the latter course of action, feel free to close this issue and just refer it to other people that ask for documentation.

**Comment by pinhopro** [comment]
Yes, I am incompetent in documenting code.   

Any help with documentation is well appreciated. 

Thanks,
Rodrigo

**Comment by pinhopro** [comment]
The "obscure gist"  ( https://gist.github.com/pinhopro/60b1fd213b36d576505e )  is not on our website because it is still not a final documentation. But the final documentation will be very similar to it. 

I really don't have too much time to invest in documentation.

**Comment by bilthon** [comment]
Hey @amingilani who do you think you are by coming here and DEMAND work to be done for you? this is an open source project where people were kind enough to make code available to you (and everybody) in the first place. Now that doesn't give you the right to demand stuff  that is not present or call people names because they don't comply. If your "forte is documented code" then the incompetent must be you.

**Comment by amingilani** [comment]
@bilthon, I would read the thread out for you, but I simply don't have the time to spell it out for you.

To anyone reading this in the future, @pinhopro's explained the API to me, i'll write the docs myself in the future.

**Comment by amingilani** [comment]
Docs now available at: https://blinktrade.com/docs/

Thanks @pinhopro!
